Installation routine ("First run") added

diff --git a/svman b/svman
--- a/svman
+++ b/svman
@@ -1,11 +1,10 @@
 #!/bin/bash
 
-temp_dir='/run'
-configs_dir=$(dirname "$0")'/svman-configs'
-SCRIPT_VERSION='0.4.26'
+configs_dir=`dirname $(realpath "$0")`/svman-configs
+SCRIPT_VERSION='0.5.27'
 backtitle_global='Wrapper for ffmpeg srt inputs v. '${SCRIPT_VERSION}
-text_editor='mcedit'
-
+text_editor=mcedit
+symlinkdir="/usr/local/bin/"
 
 trap 'exit 1;' SIGINT SIGTERM
 
@@ -24,7 +23,7 @@ export -f execute_config
 
 config_processing() {
   config_file_fullname=${whiptail_result}
-  config_description=$(basename "${config_file_fullname}" .conf)
+  config_description=$(basename "${config_file_fullname}" .preset)
   unset ${vars_needed} vars_needed
   exiting=0
   err_str=''
@@ -99,11 +98,51 @@ config_processing() {
 
 
 
+
 ######################################################################
 #                                                                    #
-# Main loop                                                          #
+# Script entry point here                                            #
 #                                                                    #
 ######################################################################
+
+
+id 'svman' 2> /dev/null 1> /dev/null
+if [[ $? -ne 0 ]] ; then
+  echo -e "User 'svman' not found. 'svman' is used for launch  ffmpeg/gstreamer sessions."
+  sudo useradd -M -r -s /usr/sbin/nologin svman
+  if [[ $? -ne 0 ]] ; then
+    exit
+  else
+    echo -ne "\n\n\nUser svman successfully added.\\n\n\nCreate symlink in ${symlinkdir}? (Y/N)"
+    while read -N 1 -n 1 -s userchoice ; do
+      if [[ 'YyNn' == *"$userchoice"* ]]; then
+        [[ 'Yy' == *"$userchoice"* ]] && ln -s $(realpath $0) ${symlinkdir}/$(basename $0)
+        break
+      fi
+    done
+  fi
+fi
+
+config_file_fullname=${configs_dir}/$(basename $0).conf
+config_file_content=();
+config_file_content+=("text_editor=mcedit");
+if [[ ! -f ${config_file_fullname} ]] ; then
+    echo -e "\n\n\nConfig file for   ===== $(basename $0) ====   not found.\n\n        It will be created now with default settings.\n        You can edit it later.\n\n\n"
+    echo -e "###############################################################"
+    echo -e "# ${config_file_fullname}"
+    echo -e "###############################################################\n#"
+    printf  "# %s\n" "${config_file_content[@]}"
+    echo -e "#\n###############################################################\n\n\n"
+    read -p "Press Enter to continue"
+    install -D <(echo 1) --mode 644 ${config_file_fullname}
+    echo -e "#\n# $(basename $0) setinngs\n#" > ${config_file_fullname}; printf  "%s\n" "${config_file_content[@]}" >> ${config_file_fullname}
+fi
+. ${config_file_fullname}
+
+
+#
+# Main loop
+#
 
 while true; do
     export NEWT_COLORS='
@@ -111,7 +150,7 @@ while true; do
       textbox=red,
     '
     [[ ! -d ${configs_dir} ]] && { whiptail --title "Config dir not found" --backtitle "${backtitle_global}" --ok-button "Exit" --msgbox "Config dir\n\n ${configs_dir}\n\n not found" 22 98 3>&2 2>&1 1>&3 ; exit; }
-    [[   -z $(find "${configs_dir}/" -name '*.conf' -print -quit) ]] && { whiptail --title "Config files not found" --backtitle "${backtitle_global}" --ok-button "Exit" --msgbox "No configs in Config dir \n\n${configs_dir}" 22 98 3>&2 2>&1 1>&3 ; exit; }
+    [[   -z $(find "${configs_dir}/" -name '*.preset' -print -quit) ]] && { whiptail --title "Config files not found" --backtitle "${backtitle_global}" --ok-button "Exit" --msgbox "No configs in Config dir \n\n${configs_dir}" 22 98 3>&2 2>&1 1>&3 ; exit; }
 
     # Build config files list
     i=0
@@ -119,8 +158,8 @@ while true; do
     unset srt_in_port;
     OLDIFS=$IFS
     IFS=$'\n' # in case of spaces in dirnames/filenames
-    for f in $(LC_ALL=C ls --format='single-column' ${configs_dir}/*.conf); do
-      tmpfname=$(basename "$f" .conf) #    ${f%.*}
+    for f in $(LC_ALL=C ls --format='single-column' ${configs_dir}/*.preset); do
+      tmpfname=$(basename "$f" .preset) #    ${f%.*}
       files[i]="$f"
       screen -ls "${tmpfname}" > //dev/null
       if [[ $? -ne 0 ]] ; then
